version: '3'
services:
  mysqldb:
    image: mysql # Use mysql image from docker hub with version 5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: Deya@12@ # Set root password for mysql
      MYSQL_DATABASE: mydb # Create a database named data_db
    ports:
      - "3307:3306"
    networks:
      - culture_network

  customer:
    build: ./client
    ports:
      - "8888:8888"
    depends_on:
      - bootstrap
    environment:
      BOOTSTRAP_URL: http://bootstrap:9090/
    networks:
      - culture_network

  bootstrap:
    build: ./bootstrap
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - node1
      - node2
      - node3
      - mysqldb
    environment:
      NODE_URL_FIRST: http://node1:27017/
      NODE_URL_SECOND: http://node2:27017/
      NODE_URL_THIRD: http://node3:27017/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mydb?allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Deya@12@
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    networks:
      - culture_network

  node1:
    build: ./node
    ports:
      - "27020:27017"
    networks:
      - culture_network

  node2:
    build: ./node
    ports:
      - "27018:27017"
    networks:
      - culture_network

  node3:
    build: ./node
    ports:
      - "27019:27017"
    networks:
      - culture_network

networks:
  culture_network:
